# Site settings
title: Natura Dev Blog
email:
author:
description:
url: ""

defaults:
- scope:
    path: "assets/images"
  values:
    image: true

# Build settings
permalink: :title/
sass:
  style: :compressed
  sass_dir: _sass

gems:
  - jekyll-paginate-v2

pagination:
  enabled: true
  locale: ''
  per_page: 9
  permalink: '/page/:num/'
