title: Natura Dev Blog
email:
author:
description:
url: ""

defaults:
- scope:
    path: "assets/images"
  values:
    image: true

permalink: :title/
sass:
  style: :compressed
  sass_dir: _sass

plugins:
  - jekyll-paginate

collections:
  category:
    output: true
