# Site settings
title: Natura Dev Blog
email:
author:
description:
url: ""

collections:
  category:
    output: true

defaults:
- scope:
    path: "assets/images"
  values:
    image: true
- scope:
    path: "category"
    type: category
  values:
    layout: "category"

# Build settings
permalink: :title/
sass:
  style: :compressed
  sass_dir: _sass
